services:
  - type: web
    name: phantom-reader
    runtime: php
    buildCommand: "bash render-build.sh"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    plan: free
    envVars:
      - key: APP_NAME
        value: PhantomReader
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error
      - key: FILESYSTEM_DISK
        value: local
